// AUTO-GENERATED from form CSV. URLs cleaned: /edit -> /view for Google Docs,
// /edit stripped from Kaggle code URLs, github/kaggle fields domain-validated.

export type Track = "flood" | "pollution";

export type Submission = {
  teamName: string;
  teamLead: string;
  track: Track;
  reportLink: string | null;
  kaggleLink: string | null;
  githubLink: string | null;
  modelCheckpointLink: string | null;
  presentationLink: string | null;
};

export type Winner = Submission & { position: 1 | 2 | 3 };

export const trackLabels: Record<Track, string> = {
  flood: "Flood Detection · IBM",
  pollution: "Pollution Forecasting · IIT Delhi",
};

export const winners: Winner[] = [
  {
    teamName: "Team Triverse",
    teamLead: "Jatin",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1CnIw4sJo_Npwf4i0rPO8XtDRpWVj_gGuJlDmcGejC38/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/jatintarange/notebookfdffe76d0d",
    githubLink: null,
    modelCheckpointLink: "https://www.kaggle.com/models/jatintarange/best-flood-1-/",
    presentationLink: "https://docs.google.com/presentation/d/1_jNqS4x5XhzK9wVs3uAj0w1RlwsmOVDn/view?usp=sharing&ouid=111759156445479506080&rtpof=true&sd=true",
    position: 1,
  },
  {
    teamName: "MEGALODON",
    teamLead: "Bhaskar",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1ZUpoeBj6wWPj4TRUdwQMXrC131BYOKas1ZhYrdW9j4o/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/competitions/anrfaisehack-theme-1-phase2/submissions",
    githubLink: "https://github.com/itikelabhaskar/AISE_PHASE2.git",
    modelCheckpointLink: "https://huggingface.co/buckets/itikelabhaskar/AISE_PHASE2",
    presentationLink: "https://iiithydresearch-my.sharepoint.com/:p:/g/personal/vijay_s_research_iiit_ac_in/IQDcTcPUNB09QY0IVeoD15oyAQfm4svFzFhvpCFUtgGGny8?e=KqDza0",
    position: 2,
  },
  {
    teamName: "Achievers",
    teamLead: "Shashwat Mishra",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1Cfrs24zoofe0zSxoqfSXIe6xPiEAE0TTrik1reYYQg4/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/srishtipandey14/notebookcc9d69eb7b",
    githubLink: "https://github.com/Shashwat-1420/Flood-mapping---AISE-Hack",
    modelCheckpointLink: "https://www.kaggle.com/datasets/shashwatm140706/flood-detection-aise-hackathon-anrf",
    presentationLink: "https://drive.google.com/drive/folders/1yiQ5fkUizFP4grtHirV_NqpXpdA01eoA?usp=sharing",
    position: 3,
  },
  {
    teamName: "VibeCoders",
    teamLead: "Pranav Mundhra",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/16dUQPQ_1d0vHWP6nEnu2f8lM_Ie1vkV6/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/meet0527/phase2-new",
    githubLink: "https://github.com/kartiks15/ANRF_AISEHack_VibeCoders",
    modelCheckpointLink: "https://www.kaggle.com/datasets/meet0527/checkpoints",
    presentationLink: "https://drive.google.com/file/d/1_hshWcapUWwVLjvo83h8opEsP8ZbSe4a/view?usp=sharing",
    position: 1,
  },
  {
    teamName: "Ctrl+alt+Defeat",
    teamLead: "Parthiv Kalikota",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/17wsWALL6KgnCePTMZYlzCdzvAWObksXI/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/saigeetesh/iiith-hack1?scriptVersionId=308979146",
    githubLink: "https://github.com/ParthivKalikota/AISEHack-Final-PollutionForecasting",
    modelCheckpointLink: "https://www.kaggle.com/code/saigeetesh/iiith-hack1/output?select=v9_best.pt",
    presentationLink: "https://docs.google.com/presentation/d/1Fr4wEQ9mR-5Hn0XSWrztAQLB4qvsATcM/view?usp=sharing&ouid=102815993790848483230&rtpof=true&sd=true",
    position: 2,
  },
  {
    teamName: "LuVW",
    teamLead: "Gautam Gandhi",
    track: "pollution",
    reportLink: "https://drive.google.com/drive/folders/16NTKEKhfbcFikJNYgUflFZ0lvhpojoH0?usp=share_link",
    kaggleLink: "https://www.kaggle.com/code/dhimantbhuva/notebookc2c8f8d722?scriptVersionId=309008189",
    githubLink: "https://github.com/Dhimant-1001/AISEHack-Phase2-PM25-Forecasting",
    modelCheckpointLink: "https://www.kaggle.com/models/dhimantbhuva/pm25-forecasting-finalsubmission",
    presentationLink: "https://drive.google.com/drive/folders/16NTKEKhfbcFikJNYgUflFZ0lvhpojoH0?usp=share_link",
    position: 3,
  },
];

export const honoraryMentions: Submission[] = [
  {
    teamName: "Earthsense",
    teamLead: "Nirdesh",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1pRouAN1s_f3bZZ3wgnCkkW7KCLBMNbb_/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/nirdeshsharma/aise-siam-train",
    githubLink: "https://github.com/der-knight/Aise_hack/tree/main",
    modelCheckpointLink: "https://www.kaggle.com/models/nirdeshsharma/siam",
    presentationLink: "https://1drv.ms/p/c/f091046558492961/IQBdZYNTQLNeSLSUv4rziFfFAXXPXA0m_5iF7B4hdHAPeAs",
  },
  {
    teamName: "hehe i do ml",
    teamLead: "Soumyajit Ghosh",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1a6CF7kXdI7k07Mbe-M7wUORpxg2PhzQe/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/momoketchum/aise-phase2-copy?scriptVersionId=309065184",
    githubLink: "https://github.com/soumomo/aisehack_hehe_i_do_ml",
    modelCheckpointLink: "https://www.kaggle.com/models/momoketchum/flood-seg-resnet101-unetpp",
    presentationLink: "https://docs.google.com/presentation/d/17_xU5x6_i0Yh9WEuwVNx7HIIAyeBW_la/view?usp=sharing&ouid=114261554377767882406&rtpof=true&sd=true",
  },
  {
    teamName: "RuVision",
    teamLead: "Raj Shah",
    track: "pollution",
    reportLink: "https://docs.google.com/document/d/1SMgufUhDlHIww4fJ0NjtuDBnmdh760eA/view?usp=sharing&ouid=100320807171952862139&rtpof=true&sd=true",
    kaggleLink: "https://www.kaggle.com/code/rajshahcx28/training-pipeline-v7",
    githubLink: "https://github.com/rajshah0928/RuVision-AISEHACK",
    modelCheckpointLink: "https://www.kaggle.com/datasets/rajshahcx28/pm25-v7",
    presentationLink: "https://docs.google.com/presentation/d/1eB8Aq8byfp84IdbUqyL9WwfYZXAsnGe8/view?usp=sharing&ouid=100320807171952862139&rtpof=true&sd=true",
  },
  {
    teamName: "Code4CleanAir",
    teamLead: "Vetriselvan R",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1nOH8NgN1ZRwPNPFkHY1dz1RnNWlZDzKR/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/greeshmasharma/notebookce92d325af?scriptVersionId=309059925",
    githubLink: "https://github.com/Vetri-78640/AISEHack-2026/",
    modelCheckpointLink: "https://www.kaggle.com/models/greeshmasharma/resgruunet",
    presentationLink: "https://www.canva.com/design/DAHF8jKeNYI/daNIeWs3sVmqUcjY6SoHiw/edit",
  },
  {
    teamName: "The Alchemists",
    teamLead: "Tanmay Porwal",
    track: "pollution",
    reportLink: "https://drive.google.com/drive/folders/1po5yEav3_NL_YEbZNpeUhNCA2iTEST9L?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/asmo04/phase-2-v2-0?scriptVersionId=309048872",
    githubLink: "https://github.com/AkshatKatiyar081/Aisehack_Final",
    modelCheckpointLink: "https://www.kaggle.com/models/asmo04/pollution-forecaster",
    presentationLink: "https://drive.google.com/drive/folders/18KxeAtPMUkgVDlVlVpqYnhzsjTn4PuNC?usp=sharing",
  },
];

export const participants: Submission[] = [
  {
    teamName: "AI-Hackers",
    teamLead: "Roshan Rateria",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1FCZYD5K2cW3nDcNU-n2aK1LInMxv_dOwQ07SsrR17Ms/view?usp=sharing",
    kaggleLink: null,
    githubLink: "https://github.com/roshanrateria/floodsense-ai",
    modelCheckpointLink: "https://huggingface.co/RoAr777/FloodSense",
    presentationLink: "https://drive.google.com/drive/folders/1i7Am0oorYT3JZ6Wt-6lovioJjxQhySJ-?usp=sharing",
  },
  {
    teamName: "AquaSentinels",
    teamLead: "Saanvi Belede Naga",
    track: "flood",
    reportLink: "https://drive.google.com/drive/folders/1gTJ1dbOxlpqrgS3tVGxKrgRNKZvlywzn?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/saanvibeledenaga/aquasentinels-top-model-phase-2-aisehack",
    githubLink: "https://github.com/kushisafk/AISEHack",
    modelCheckpointLink: "https://www.kaggle.com/models/kushsaha/flood-segmentation-model-aisehack",
    presentationLink: "https://drive.google.com/drive/folders/1r9PimLmo7BAsbApq-ps3nRLLnRz-Pp4R?usp=sharing",
  },
  {
    teamName: "BASIKA VAMSHI",
    teamLead: "BASIKA VAMSHI",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1D_iWYTiquH_T8jC7T7UeqOCt9ZSIPpxeuQDJOeY7RUQ/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/rockyvillagegaming/notebookee0ada3cf8/notebook?scriptVersionId=308749111",
    githubLink: "https://github.com/Basikavamshi/Flood-Segmentation",
    modelCheckpointLink: "https://www.kaggle.com/models/rockyvillagegaming/flood-segmentation-model",
    presentationLink: "https://drive.google.com/file/d/1LkLGjCTaBuhMQmJh6S1EPSSuO3d5jzbZ/view?usp=sharing",
  },
  {
    teamName: "Binary Blinders",
    teamLead: "Nihash S",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1pY7lDNX1CT38XEqkGW_HgnHxSLaHqa6w/view?usp=drive_link",
    kaggleLink: "https://www.kaggle.com/code/nihashkishore2006/best-phase-2",
    githubLink: null,
    modelCheckpointLink: "https://www.kaggle.com/models/nihashkishore2006/flood-detectionbb",
    presentationLink: "https://docs.google.com/presentation/d/1gcau6FSSIhpUNhwCyQhHCxjAEg2o8xiqQIE2puxnTTI/view?usp=sharing",
  },
  {
    teamName: "Binary Bombers",
    teamLead: "Mohit Bhutada",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1ySO7cT3DlYjzgOoMKpgyWhQODlh-20QP/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/mohitbhutada28/mohit-n1run/309032975",
    githubLink: "https://github.com/mohit-bhutada/Binary-Bombers",
    modelCheckpointLink: "https://huggingface.co/sumit1703/Pollution_Forcasting_Binary_bombers/blob/main/preds.npy",
    presentationLink: "https://docs.google.com/presentation/d/1_LGnZjb1SQ7sNq_LZtsvGtjdAJMu2DuYoq2Ay8aACAs/view?usp=sharing",
  },
  {
    teamName: "Bright",
    teamLead: "kusuma gurram",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1wq87jx3zGssk-1vu9JDDhAtG7InNlPo4/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/chetanf01/sumission01",
    githubLink: "https://github.com/kusuma2506/aisefinal.git",
    modelCheckpointLink: "https://www.kaggle.com/code/chetanf01/sumission01",
    presentationLink: "https://docs.google.com/presentation/d/1XUOWXsV39ljy4gbYG7VeQYFrpxAqTJSC/view?usp=sharing&ouid=110370403267797435298&rtpof=true&sd=true",
  },
  {
    teamName: "CODE CREW",
    teamLead: "Roshan Shaik",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/13MKG5lZLlLYIRd4m4229lohUluOA7kgHxJ0kOVR0r1E/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/madhuveer098/code-crew-77?scriptVersionId=309072618",
    githubLink: "https://github.com/BhavyaKonagala/AISEHack-CODE-CREW",
    modelCheckpointLink: "https://www.kaggle.com/datasets/madhuveer098/flood-detection-model-checkpoint",
    presentationLink: "https://docs.google.com/presentation/d/1jKn-eNKc0EskVm92sllwUqi-aDDCILtM/view?usp=sharing&ouid=110779439855236129553&rtpof=true&sd=true",
  },
  {
    teamName: "Coding Brigades",
    teamLead: "Hemant Pande",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1qBmYR9wqoLE7rb5ImUkB1HrQrTATLFEF2oPMdW44vos/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/hemantpande05/phase-2-version-2",
    githubLink: "https://github.com/HEMANT-PANDE/Final-Submission-AISEHack",
    modelCheckpointLink: "https://www.kaggle.com/models/hemantpande05/flood-segmentation-unet-model-aisehack-2026",
    presentationLink: "https://drive.google.com/file/d/1F1iRZb7Qc2MCe5x3-MUsZP9zMUMoKMqC/view?usp=sharing",
  },
  {
    teamName: "Colab Survivors",
    teamLead: "Md Kaif Imteyaz",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/16OS3JZUZSzlWUe84YxxJbnblNXi8t0xm/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/kaifimtz/preds-npy",
    githubLink: "https://github.com/Kaif-Imteyaz/ANRF-AISEHack-Phase-2-Th2-Pollution-Forecasting",
    modelCheckpointLink: "https://www.kaggle.com/datasets/kaifimtz/colab-survivors-pm2-5-phase-2-best-checkpoint",
    presentationLink: "https://docs.google.com/presentation/d/1GqkHOoVTRjEJUa4n3UYmTAfIiHqmUi8s/view?usp=drive_link&ouid=117029939678558831266&rtpof=true&sd=true",
  },
  {
    teamName: "Deep Thinkers",
    teamLead: "oindrieel mondal",
    track: "flood",
    reportLink: "https://drive.google.com/drive/folders/1bDKA2rv3TrJvUyRIUeptX6otDQ53gPEO?usp=drive_link",
    kaggleLink: "https://www.kaggle.com/code/tannisthab/final-v3?scriptVersionId=308784452",
    githubLink: "https://github.com/oindrieel/ANRF-PHASE-2-THEME-1/tree/main?tab=License-1-ov-file#readme",
    modelCheckpointLink: "https://drive.google.com/drive/folders/1A9gL3N3P9QJ3KQjX8-6a5F_3cZtfOH_X?usp=drive_link",
    presentationLink: "https://drive.google.com/drive/folders/1rmmk4XqsnVHWUbHxd-1gW765HFn9OI62?usp=drive_link",
  },
  {
    teamName: "Elite Squad",
    teamLead: "Rakshitha",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1ETdGFRbXCrH1iMCq3n8m6KO-wL7qcZL-/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/rextonwolf/code-7?scriptVersionId=308610399",
    githubLink: "https://github.com/jc-kirthi/Elite-Squad",
    modelCheckpointLink: "https://huggingface.co/jc-kirthi/Elite-Squad",
    presentationLink: "https://drive.google.com/file/d/1a8AzWh_B65yBuhdPNAiLqpKwDuxDurY6/view",
  },
  {
    teamName: "ESPRIT",
    teamLead: "Yash Kumavat",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1jZN6MqLLzRkfAlV3vrukCrRpqVZlpwDp/view?usp=drive_link",
    kaggleLink: "https://www.kaggle.com/code/yashkumavat/yash-unet/notebook?scriptVersionId=308945807",
    githubLink: "https://github.com/FamYash/ANRF-AISEHack-Phase-2-Theme-2-ESPRIT",
    modelCheckpointLink: "https://www.kaggle.com/models/yashkumavat/unet",
    presentationLink: "https://drive.google.com/file/d/1B111cO_bjvm0OpWGzfcmzVtjq6QUPm7R/view?usp=drive_link",
  },
  {
    teamName: "Evaluation Error",
    teamLead: "Kalva Kavya",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1ePCc5UG3LlUmkSQokBoykqkBnTk_NdqcV-pTOVjfRUQ/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/someshtellakula/flooddoubles-6?scriptVersionId=309061244",
    githubLink: "https://github.com/kavyakalva08/Flood_detection_AISE",
    modelCheckpointLink: "https://www.kaggle.com/models/kavyakalva08/flood-segmentation-resnet50-aise",
    presentationLink: "https://docs.google.com/presentation/d/1TmeP46SSacHJe2N0JHTr4HyYZt_hiNGv/view?usp=sharing&ouid=113097859793819298977&rtpof=true&sd=true",
  },
  {
    teamName: "Exceptionists",
    teamLead: "Ragini R",
    track: "flood",
    reportLink: "https://docs.google.com/presentation/d/1z_LK0j82wGwBrueZjCxBsfZZ2gDMpw3m/view?usp=drive_link&ouid=103705674283493532211&rtpof=true&sd=true",
    kaggleLink: "https://www.kaggle.com/code/sanjaymstack/version-7",
    githubLink: "https://github.com/Ragini2811/Flood_Detection_IBM",
    modelCheckpointLink: "https://www.kaggle.com/datasets/raginir2811/prithvi-weights",
    presentationLink: "https://docs.google.com/presentation/d/1z_LK0j82wGwBrueZjCxBsfZZ2gDMpw3m/view?usp=drive_link&ouid=103705674283493532211&rtpof=true&sd=true",
  },
  {
    teamName: "Femme Coders",
    teamLead: "Suyashi Tiwari",
    track: "pollution",
    reportLink: "https://docs.google.com/document/d/1cA2QCmOwXSw9Dh0QZ_GQeEyfFcGbYwnSmTm9IIol6Mo/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/shivangisingh2101/notebookfe9315275f",
    githubLink: "https://github.com/suyashitiwari4",
    modelCheckpointLink: null,
    presentationLink: null,
  },
  {
    teamName: "GreenNeurons",
    teamLead: "Pranjay Srivastava",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1Tyz1fQQ9Fpbe5Hm_VMDg-f1--I21GwBD/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/pranjay2006/first?scriptVersionId=309058541",
    githubLink: "https://github.com/PranjaySrivastava/GreenNeurons/tree/main",
    modelCheckpointLink: "https://www.kaggle.com/models/pranjay2006/greenneurons",
    presentationLink: "https://docs.google.com/presentation/d/1oQoAj4C7SHrOaLqMC2YFDCpew8EHUOYE/view?usp=sharing&ouid=102666593396025011348&rtpof=true&sd=true",
  },
  {
    teamName: "Hackonauts",
    teamLead: "Mokshajna Undavalli",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/187fSi3osPA8e5lqOCji5ZYIAODmUa5K9/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/mokshajnaundavalli/aise6run/308950262",
    githubLink: "https://github.com/vijayesh11/Hackonauts_Final_AISE",
    modelCheckpointLink: "https://www.kaggle.com/datasets/mokshajnaundavalli/aisehack-phase2-top-submission-weights/data/data/data",
    presentationLink: "https://docs.google.com/presentation/d/1EbMZR6dJCG0nvsWjVWRlMf04LynnjY6M/view?usp=sharing&ouid=105953175001984281672&rtpof=true&sd=true",
  },
  {
    teamName: "Hala Madrid",
    teamLead: "Jana Krisna B",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1zxzY2SfPvdP8FM-rRcR7Oyb0PZAmKZU0/view?usp=sharing&ouid=114590194593516984040&rtpof=true&sd=true",
    kaggleLink: "https://www.kaggle.com/code/janakrisna/notebook471fe97b61?scriptVersionId=309071553",
    githubLink: "https://github.com/keertansatish/AISHE-FINAL_SUBMISSION-Flood-Detection-.git",
    modelCheckpointLink: "https://drive.google.com/file/d/1y2T66cFv663eqARhcO4dbaxZe2hTepD9/view?usp=sharing",
    presentationLink: null,
  },
  {
    teamName: "Heisenberg",
    teamLead: "T.Jhansi Chandra Reddy",
    track: "flood",
    reportLink: null,
    kaggleLink: "https://www.kaggle.com/competitions/anrfaisehack-theme-1-phase2/submissions#",
    githubLink: "https://github.com/vinuthanreddybanda/ANRF-AISE-Flood-detection-model-",
    modelCheckpointLink: "https://www.kaggle.com/datasets/winuthanreddy/aisehack-phase2-checkpoints",
    presentationLink: "https://docs.google.com/presentation/d/1tYl3NR-oJFE3oe9FUXJgYw0-s54cxnJD/view?usp=sharing&ouid=108990559503970779365&rtpof=true&sd=true",
  },
  {
    teamName: "House Targaryen",
    teamLead: "Rahul Gupta",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1ueZQOW42Bj_kIU7PIVXBflUpdujLarUAnAZceB7k29c/view?tab=t.0#heading=h.kcb4ro7zu9so",
    kaggleLink: "https://www.kaggle.com/code/rahulguptaiiitd/0-1757?scriptVersionId=309076754",
    githubLink: "https://github.com/Ashish-waiker/AISE_Hackathon/tree/master",
    modelCheckpointLink: "https://drive.google.com/file/d/1eI0G0fF3fVeCljLGaLLZJToNH_ouaEPz/view?usp=sharing",
    presentationLink: "https://docs.google.com/presentation/d/1oCHSTuAFICKd2b60TiyzYADKtyAYXz_T/view?usp=sharing&ouid=115193234667706517978&rtpof=true&sd=true",
  },
  {
    teamName: "Infinity Loop",
    teamLead: "Snigdha Talasila",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1c8P4MxdJmRNZXIWqB77JL44kc4Hrefoo/view?usp=sharing&ouid=106535697178272838136&rtpof=true&sd=true",
    kaggleLink: "https://www.kaggle.com/code/snigdhatalasila/notebook8d9ea83b02",
    githubLink: "https://github.com/harini98667755/Flood-detection/tree/main",
    modelCheckpointLink: "https://www.kaggle.com/models/snigdhatalasila/flood",
    presentationLink: "https://docs.google.com/presentation/d/14hs1j2EL-TkkUPfRB1U54m15Bu_40P5E/view?usp=sharing&ouid=116681409780285759820&rtpof=true&sd=true",
  },
  {
    teamName: "Innovatrix",
    teamLead: "Lahari Guggilam",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1NIHhVRbTO1EE5zI69FHsY3KCnw121O-i/view?usp=sharing&ouid=112596672774597818595&rtpof=true&sd=true",
    kaggleLink: "https://www.kaggle.com/code/lahariguggilam/trail5",
    githubLink: "https://github.com/Lahari-Datascience/Flood-Detection/blob/main/trail5.ipynb",
    modelCheckpointLink: "https://www.kaggle.com/code/lahariguggilam/trail5",
    presentationLink: "https://docs.google.com/presentation/d/1Hnk16c_QNFDksKKhVmSOPMMr-Rl2OOT0/view?usp=sharing&ouid=112596672774597818595&rtpof=true&sd=true",
  },
  {
    teamName: "JAEGERISTS",
    teamLead: "AZHAGAN S",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1D6xaMguUMi-k3yPzxhYMMMTEs2V-rPwa/view?usp=drive_link",
    kaggleLink: "https://www.kaggle.com/code/krishnagaraa/aise-anrf-phase-2run/309045611",
    githubLink: "https://github.com/Azhagan-24/AIR-POLLUTION",
    modelCheckpointLink: "https://www.kaggle.com/code/tumpanjawat/diabetes-eda-random-forest-hp",
    presentationLink: "https://docs.google.com/presentation/d/1Xk5r1s8DaU56YsWeYeTkMlv7K6BMRp_o/view?usp=drive_link&ouid=102150428405594545345&rtpof=true&sd=true",
  },
  {
    teamName: "Meghdoot",
    teamLead: "Siddharth Brijesh Tripathi",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1K_4_R81HK8RRbrk9uZSs7n5Sw9G5Dmm-/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/sidtri26/meghdoot-aise-phase2",
    githubLink: "https://github.com/sidtricoder/aisehack-phase-2/tree/main",
    modelCheckpointLink: "https://www.kaggle.com/code/sidtri26/meghdoot-submission",
    presentationLink: "https://drive.google.com/file/d/1K_4_R81HK8RRbrk9uZSs7n5Sw9G5Dmm-/view?usp=sharing",
  },
  {
    teamName: "merge conflict",
    teamLead: "sandeep sarkar",
    track: "flood",
    reportLink: "https://drive.google.com/drive/folders/1zXrPRDqdBaye05xS412EFHHqQwOqoViE?usp=sharing",
    kaggleLink: "https://www.kaggle.com/competitions/anrfaisehack-theme-1-phase2/submissions#",
    githubLink: "https://github.com/sandy4242/merge-conflict",
    modelCheckpointLink: null,
    presentationLink: "https://drive.google.com/drive/folders/1ahTkyjRbMsrkiuHNbq2kn9uhG_wUnbjQ?usp=sharing",
  },
  {
    teamName: "NEURAL SHINOBI",
    teamLead: "DEVESH POOJARY",
    track: "pollution",
    reportLink: "https://docs.google.com/document/d/1WRL3P5UUcr6O_NcyWIqoa7FpwVSk6FKrkPG1Lf7VAw8/view?tab=t.0",
    kaggleLink: "https://www.kaggle.com/code/adityaeh/futureensemble?scriptVersionId=308954743",
    githubLink: "https://github.com/hippomasters/AISEHACK-PHASE-2.git",
    modelCheckpointLink: "https://www.kaggle.com/models/adityaeh/futureensemble/",
    presentationLink: "https://docs.google.com/presentation/d/1kk8aJQQubqSayt7mfzOF4X9mrz5UcmRnal-ZWXYVKzA/view?usp=sharing",
  },
  {
    teamName: "Nexus Solvers",
    teamLead: "Mayank Ninawe",
    track: "flood",
    reportLink: "https://drive.google.com/drive/folders/1Yf5vRmiAd-nH_XtH_pSt0uIp-JLBhfW5?dmr=1&ec=wgc-drive-%5Bmodule%5D-goto",
    kaggleLink: "https://www.kaggle.com/code/a335hariomrathod/lb06-mayank-unetpp-b4-binary-flood-cv5/notebook?scriptVersionId=308858440",
    githubLink: "https://github.com/zeba-source/ANRF-AISE-Flood-Segmentation-with-U-Net-Team-Nexus-Solvers/tree/main",
    modelCheckpointLink: "https://huggingface.co/khanzebafatma/AISEHACKTHEME1/tree/main",
    presentationLink: "https://docs.google.com/presentation/d/1BFToTU5Dp8EN8p5b87acXaA_WS1a_fyP/view",
  },
  {
    teamName: "NITC",
    teamLead: "Balaji R",
    track: "flood",
    reportLink: "https://drive.google.com/drive/folders/101Fzlox4qywMzSoQRxAMhqJyILYlJDSv",
    kaggleLink: "https://www.kaggle.com/code/adithyar21510/notebook3bed3d57b3/",
    githubLink: "https://github.com/BalajiR20/ANRF-AISEHack-Phase-2-Theme-1-Flood-Detection-IBM",
    modelCheckpointLink: "https://github.com/BalajiR20/ANRF-AISEHack-Phase-2-Theme-1-Flood-Detection-IBM",
    presentationLink: "https://drive.google.com/drive/folders/101Fzlox4qywMzSoQRxAMhqJyILYlJDSv",
  },
  {
    teamName: "Outliers",
    teamLead: "Netram Faran",
    track: "flood",
    reportLink: "https://drive.google.com/drive/folders/1BMMrvDeVVHsA4g6amOPlyWjOGNIPIOXK?usp=drive_link",
    kaggleLink: "https://www.kaggle.com/code/ravijotsinha/32-patches-unet",
    githubLink: "https://github.com/netram75/aisehack-flood-segmentation.git",
    modelCheckpointLink: "https://www.kaggle.com/models/ravijotsinha/unet-with-32-patches-checkpoint",
    presentationLink: "https://drive.google.com/drive/folders/1BMMrvDeVVHsA4g6amOPlyWjOGNIPIOXK?usp=drive_link",
  },
  {
    teamName: "PeakyCoders",
    teamLead: "Nallabantu Hareeswar",
    track: "pollution",
    reportLink: "https://docs.google.com/document/d/1FjnzwTk0b-9mJhQDGI5uBOZymqNb7Jnf/view?usp=sharing&ouid=110666908096900405713&rtpof=true&sd=true",
    kaggleLink: "https://www.kaggle.com/code/nallabantuhareeswar/notebookd1f97cd069",
    githubLink: "https://github.com/DS-SAi2005/hybrid-fno-gru-pm25",
    modelCheckpointLink: "https://drive.google.com/file/d/1-dG3EDgFr3c3dP1chPAaZnxUvGelkRuu/view?usp=sharing",
    presentationLink: "https://drive.google.com/drive/folders/1VjNOxFgAMLdCz3qY7ds15A_E_iL7vMza?usp=sharing",
  },
  {
    teamName: "Powerx",
    teamLead: "Sukesh M",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1bpl_pCcWvs0CeWvQhxPxlkse7ZgIxtgl/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/sangsaist/prithivi-model-2?scriptVersionId=308941166",
    githubLink: "https://github.com/sangsaist/powerx.git",
    modelCheckpointLink: "https://www.kaggle.com/code/sangsaist/prithivi-model-2?scriptVersionId=308941166",
    presentationLink: "https://docs.google.com/presentation/d/1WY5a2SUefs-9ybxeKAjSJXVnRPLotQQd/view?usp=sharing&ouid=105458206209203269293&rtpof=true&sd=true",
  },
  {
    teamName: "Quantum and AI Team CDAC CINE",
    teamLead: "Vinayaka poorma",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1VMUm68-GdWxpOU2dqKLyVPrWyurpCNZJ/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/fardinrohman/aisehack-ph2-final-submission/",
    githubLink: "https://github.com/Laxus12/AISEHack2026-Theme_1",
    modelCheckpointLink: "https://www.kaggle.com/models/vinayakapoorma1810/aisehackhase2finalsubmissioncdac",
    presentationLink: "https://docs.google.com/presentation/d/1vTE9qyHLNqOOE3xLhInTiKMaRNC0RQlI/view?usp=sharing&ouid=104751572818551109706&rtpof=true&sd=true",
  },
  {
    teamName: "Runtime Rebel's",
    teamLead: "Jagarlamudi Dhamarukanath",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1aO8P6caM5ulHu24h2Ajxnd1Xo10fDJHu/view?usp=sharing&ouid=108287344255043636372&rtpof=true&sd=true",
    kaggleLink: "https://www.kaggle.com/code/sharathchandra06/runtime-rebels",
    githubLink: "https://github.com/shiva13-ai/AiSE-Hack-Runtime_Rebel-s",
    modelCheckpointLink: "https://www.kaggle.com/models/dhamarukanath/flood-segmentation-unetplusplus",
    presentationLink: "https://docs.google.com/presentation/d/1ebRRQitUeOq3XItrkfD5SgjxYKbhhaRd/view?usp=sharing&ouid=108287344255043636372&rtpof=true&sd=true",
  },
  {
    teamName: "S.Lasyapriya",
    teamLead: "S.Lasyapriya",
    track: "pollution",
    reportLink: "https://1drv.ms/w/c/724487e0724dfdd0/IQARxn4Z2-CAQIhqI0i_O6jJAQ_0fNyt6WLkXECyUDR1lqw?e=1yqAW0",
    kaggleLink: "https://www.kaggle.com/code/slasyapriya/notebook3e457bad7c",
    githubLink: "https://github.com/sabbanilasyapriya-lgtm/PM25-Forecasting-AI.git",
    modelCheckpointLink: "https://www.kaggle.com/datasets/slasyapriya/notebook85bb8a15fb",
    presentationLink: "https://1drv.ms/p/c/724487e0724dfdd0/IQDFaOh5cDK0Tr8aZdrF2hK5ATaLVmcosn5cWOH6kYvU-6I?e=YnBb8S",
  },
  {
    teamName: "Seg Faults",
    teamLead: "Koduru Jagrutha Aditya",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1jTGQ8QN3dN1hYGB4IRTxJ1o1exgJUIql/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/jagruthaadityakoduru/2-stage-model?scriptVersionId=309058222",
    githubLink: "https://github.com/kja8586/AISEHackPhase2Theme1",
    modelCheckpointLink: "https://www.kaggle.com/models/jagruthaadityakoduru/phase1-unet-maxvit;https://www.kaggle.com/models/jagruthaadityakoduru/2-stage-model;https://www.kaggle.com/models/jagruthaadityakoduru/unet-for-floodsegmentation;https://www.kaggle.com/models/jagruthaadityakoduru/segformer-for-floodsegmentation",
    presentationLink: "https://docs.google.com/presentation/d/18wml6unvqsk60GXOPqheDFUA8AuU4LOb/view?usp=sharing&ouid=115026213911999849300&rtpof=true&sd=true",
  },
  {
    teamName: "Siddharthians",
    teamLead: "Eshwar Vijay Dheeraj Kollati",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1Q5vod5elMZNnLKmroA1lbD0mfzS2eTBf/view",
    kaggleLink: "https://www.kaggle.com/code/eshwarvijaydheeraj/deeplabv3/",
    githubLink: "https://github.com/nabro356/Siddharthians_AISEHack",
    modelCheckpointLink: "https://www.kaggle.com/models/eshwarvijaydheeraj/anrf-model",
    presentationLink: "https://docs.google.com/presentation/d/1Vva7HSbaOCDDT5BMoRHAxWB_4BQ6kM_T/view?usp=sharing&ouid=113866851866161189181&rtpof=true&sd=true",
  },
  {
    teamName: "standardBasis",
    teamLead: "Yash Sorathiya",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1a_d7fS14u-PsJO54BBKwzwfMquvX-wldAfT45kjucu0/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/jenishsorathiya/phase-2-inference-prithvi-300m-tl?scriptVersionId=309048689",
    githubLink: "https://github.com/Yashraj009/ANRF-AISE-Hack-Flood-Detection/",
    modelCheckpointLink: "https://www.kaggle.com/models/yashsorathiya009/standardbasis-best-model-checkpoints/",
    presentationLink: "https://drive.google.com/drive/folders/1lSP4i7j2T2pAXcStwQa80SLYrOJL9PtF?usp=sharing",
  },
  {
    teamName: "Synergy",
    teamLead: "Aadrika Gupta",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/18i7SbebdE4ar1mIJq1gd9YKvHHw0klmj/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/aadrikagupta21/notebook16",
    githubLink: "https://github.com/Sangyan1234/PM2.5-Multimodel-Ensemble",
    modelCheckpointLink: "https://www.kaggle.com/code/aadrikagupta21/notebook16",
    presentationLink: "https://docs.google.com/presentation/d/1dNnjQX_OikM1YA1tAQvqgeEqEUBFUl1O/view?usp=sharing&ouid=100044279608316487953&rtpof=true&sd=true",
  },
  {
    teamName: "TamilRockers.tn",
    teamLead: "Gunaselan S V",
    track: "pollution",
    reportLink: "https://docs.google.com/presentation/d/1cuuP0HwC3RWQTAprJ52FRUh3XZubYrAc/view?usp=drive_link&ouid=105591152564407442855&rtpof=true&sd=true",
    kaggleLink: "https://www.kaggle.com/code/megaanthc/meganath-ph2/notebook?scriptVersionId=309021716",
    githubLink: "https://github.com/Gunaselan1201/TamilRockers.tnN/",
    modelCheckpointLink: "https://www.kaggle.com/code/megaanthc/meganath-ph2/notebook?scriptVersionId=309021716",
    presentationLink: "https://docs.google.com/presentation/d/1cuuP0HwC3RWQTAprJ52FRUh3XZubYrAc/view?usp=drive_link&ouid=105591152564407442855&rtpof=true&sd=true",
  },
  {
    teamName: "tanbirisme",
    teamLead: "Tanbir Aproose Laskar",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1SMXlGbBYMPR3Po94POmtVSmikCI9N_qJeGxo4-ndCu0/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/competitions/anrfaisehack-theme-1-phase2/submissions#",
    githubLink: "https://github.com/pratyush-015/FloodDetection_Phase2",
    modelCheckpointLink: "https://www.kaggle.com/models/tanbirisme/flood-seg-nits",
    presentationLink: "https://docs.google.com/presentation/d/1ZeBOidUFBLeTZ37m_uctpZ8LwzrRXv0vMfuje9LBGD0/view?usp=sharing",
  },
  {
    teamName: "Team AG",
    teamLead: "K N S Sri Harshith",
    track: "pollution",
    reportLink: "https://docs.google.com/document/d/1jR05Cn1x1_mRXoNgGKZJy4I8wb7ZIwEncMfs031d6QM/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/notme1725/notebook14f85cd925?scriptVersionId=308918821",
    githubLink: "https://github.com/shashanksuri616/AiseHack-Team-AG-Final",
    modelCheckpointLink: "https://www.kaggle.com/models/suryaalakanti/team-ag-convlstm-u-net",
    presentationLink: "https://docs.google.com/presentation/d/1sPRVes2vTZ2xbkO05jpG-JmrXKSjsuJB/view?usp=sharing&ouid=116666723282613380205&rtpof=true&sd=true",
  },
  {
    teamName: "Team ENDRA",
    teamLead: "Somesh Padsalge",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1R8THsmT_D0JXZRRRKORGC7O22UJgHVc_37iV590sSuw/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/someshpadsalge/best-best0-1593",
    githubLink: "https://github.com/AbhayKale332/Team-ENDRA-AISEHack",
    modelCheckpointLink: "https://www.kaggle.com/code/someshpadsalge/best-best0-1593/output?scriptVersionId=309061668",
    presentationLink: "https://docs.google.com/presentation/d/13cPXv2wFSgvpeaSxakgRtowvzLtnoUNfETPz-628d-8/view?usp=sharing",
  },
  {
    teamName: "Team Lakshya",
    teamLead: "Tanisha Sharma",
    track: "flood",
    reportLink: "https://docs.google.com/document/d/1iqkxNV-HG7Pe5JW9iCu5xIlyatJXSgwhz1hfUNSAkxw/view?tab=t.y58sfz16n6hv",
    kaggleLink: null,
    githubLink: "https://github.com/Tanisharma122/AISEHack-2026-Phase-2-Team-Lakshya-/tree/main",
    modelCheckpointLink: "https://drive.google.com/drive/folders/1h-CttIsghqVUlBwZwZCGbbdo_l2JfL_0?usp=sharing",
    presentationLink: "https://docs.google.com/presentation/d/1eHd8iRU8wIgcXYRITYcBXOcdfiQDhvYR/view?usp=sharing&ouid=108610975770940243713&rtpof=true&sd=true",
  },
  {
    teamName: "Team Vega",
    teamLead: "Murtuza Shaikh",
    track: "pollution",
    reportLink: "https://docs.google.com/document/d/17iA7hdzajfKC2M_INo97bV4Z-2Bj-pj4xAPSDqrSmbc/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/ronitraj1/exp07",
    githubLink: "https://github.com/Ronit-Raj9/aisehack_phase2_submission/",
    modelCheckpointLink: "https://huggingface.co/ronitraj/pm2.5_predictor",
    presentationLink: "https://canva.link/m94qm6aw0w0xln7",
  },
  {
    teamName: "TEAM XD",
    teamLead: "T.SUSHMIDHA",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1Rv1TPHqaTB4AJVV9V_plqI57Yt_KdUDS/view?usp=sharing",
    kaggleLink: null,
    githubLink: "https://github.com/sushmidhathakur/AISEHack-MID-Submission.git",
    modelCheckpointLink: null,
    presentationLink: "https://drive.google.com/file/d/1Rv1TPHqaTB4AJVV9V_plqI57Yt_KdUDS/view?usp=sharing",
  },
  {
    teamName: "TECHSPARKS",
    teamLead: "B ROHAN SAI",
    track: "pollution",
    reportLink: "https://docs.google.com/document/d/1hjHV7pqW34K-oXgzfxJw8xy82NCAV-uamhGJBcluCR0/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/srivatsakaustubh/phase-4?scriptVersionId=308972192",
    githubLink: "https://github.com/Rohan-07-c/ANRF-LICENSE/tree/main",
    modelCheckpointLink: "https://www.kaggle.com/datasets/sakethduvvuri/aise-anrf-phase2",
    presentationLink: "https://docs.google.com/presentation/d/1pty-PWE69LTFGO2rB321G1AEE81AxRTm/view?usp=sharing&ouid=105496449029693500863&rtpof=true&sd=true",
  },
  {
    teamName: "TON_618",
    teamLead: "Ganduri Sai Kousik",
    track: "pollution",
    reportLink: "https://docs.google.com/document/d/1N6ZK3hsTuEjO-UKDW5mSUnB3h9Gwc8lIl5PxDiLXLfo/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/gajjalachaithanya/notebookcbc2eb9ebd",
    githubLink: "https://github.com/saikousikganduri01/AISEHACK_TON618.git",
    modelCheckpointLink: "https://drive.google.com/drive/folders/1zXItH3cjGfgGvWQc71CDV7oivTrAHpmF?usp=sharing",
    presentationLink: "https://docs.google.com/presentation/d/1a2tUsNhxHeGMar1_FnhwpZNQXUmDx870/view?usp=sharing&ouid=102950655714828303635&rtpof=true&sd=true",
  },
  {
    teamName: "VayuScope",
    teamLead: "Katta Ram Sai Nuthan",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1bJVXaeX5N-E13FW1Xjlda3VBB1sQZ3p7/view?usp=drive_link",
    kaggleLink: "https://www.kaggle.com/code/akiraaravind/notebook72153b7ce7",
    githubLink: "https://github.com/KushalManikonda/AISE-Hack-VayuScope",
    modelCheckpointLink: "https://www.kaggle.com/models/nuthankatta/anrf-aise-vayuscope",
    presentationLink: "https://docs.google.com/presentation/d/11ixWkncbQpx-16ZUfTh4X4alzGV-qrrusHMJWvHWJdo/view?usp=sharing",
  },
  {
    teamName: "VU-RYZEN",
    teamLead: "Vemula Harshith",
    track: "pollution",
    reportLink: "https://drive.google.com/file/d/1B_487p2U5nrHHGlt12nNhIhBxHAYjwhD/view?usp=drive_link",
    kaggleLink: "https://www.kaggle.com/code/harshithvemula/trail-04",
    githubLink: "https://github.com/Lakshman-2558/AISEHACK-VU-RYZEN",
    modelCheckpointLink: "https://www.kaggle.com/code/harshithvemula/trail-04",
    presentationLink: "https://docs.google.com/presentation/d/1NqbGzTT6Ysyob3sBb0CFhS5ry2fALWr0/view?usp=sharing&ouid=113561334971606017463&rtpof=true&sd=true",
  },
  {
    teamName: "who-knows",
    teamLead: "Devam Shah",
    track: "flood",
    reportLink: "https://drive.google.com/file/d/1TDES-5eS9BGt0DOSGhKCcWvrR1-1gola/view?usp=sharing",
    kaggleLink: "https://www.kaggle.com/code/devamwppu2000828/anrf-aisehack-flood-detection-adlinknet",
    githubLink: "https://github.com/Devamm007/aisehack1-flood-detection",
    modelCheckpointLink: "https://www.kaggle.com/models/devamwppu2000828/aisehack-flood-unetpp-efficientnet-b5/pyTorch/v3",
    presentationLink: "https://docs.google.com/presentation/d/1J7TaIJzSZRpuEk_0pRPMWV6-rOGUxtNx/view?usp=sharing&ouid=112811014835346445613&rtpof=true&sd=true",
  },
];

